twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        categoriesRepository: '@App\Repository\CategoryRepository'
        plateformesRepository: '@App\Repository\PlateformeRepository'
        genresRepository: '@App\Repository\GenreRepository'
        gamesRepository: '@App\Repository\GamesRepository'


