twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        categoriesRepository: '@App\Repository\CategoryRepository'
        plateformesRepository: '@App\Repository\PlateformeRepository'
        genresRepository: '@App\Repository\GenreRepository'
        gamesRepository: '@App\Repository\GamesRepository'


